version: "3"
services:
    api:
      build: 
        context: ./backend
        args: 
          NODE_ENV: development
      volumes: 
        - ./backend/:/usr/src/app/
        - /usr/src/app/node_modules
      environment: 
        - NODE_ENV=development
      env_file:
        - ./backend/.env
      command: npm run dev
    frontend:
      build:
        context: ./frontend
      volumes:
        - ./frontend/:/app
      env_file:
        - ./frontend/.env
      command: npm run start
